version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "addvalue-agent-backend"
s3_prefix = "addvalue-agent-backend"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"production\" AllowedOrigin=\"https://main.your-app-id.amplifyapp.com\" RecipientEmail=\"adobaryuyanglianluoyongshishiy@gmail.com\""
resolve_s3 = true
confirm_changeset = true
image_repositories = []
disable_rollback = true
